#!/usr/bin/env sh
set -ue

ok=1

for day in $(seq 1 25); do
	f_correct="$(printf './txt/correct/%.2d.txt' $day)"
	if [ ! -f "$f_correct" ]; then
		continue;
	fi
	printf 'day %.2d: ' $day
	expect="$(cat "$f_correct")"
	output="$(./solve $day)"
	if [ "$output" != "$expect" ]; then
		printf "fail\n"
		ok=
	else
		printf "ok\n"
	fi
	printf 'expect: %s\n' "$expect"
	printf 'output: %s\n' "$output"
	printf '\n'
done

if [ ! $ok ]; then
	exit 1;
fi
