#!/usr/bin/env sh
set -ue

ok=1

for day in $(seq 1 25); do
	if [ $# -eq 1 ]; then
		if [ $day -ne $1 ]; then
			continue;
		fi
	fi
	f_correct="$(printf './txt/correct/%.2d.txt' $day)"
	if [ ! -f "$f_correct" ]; then
		continue;
	fi
	printf 'day %.2d: ' $day | tee -a test.stderr
	expect="$(cat "$f_correct")"
	output="$(make run_d$(printf '%.2d' $day) 2>> 'test.stderr')"
	if [ "$output" != "$expect" ]; then
		printf "fail\n"
		ok=
	else
		printf "ok\n"
	fi
	printf 'expect: %s\n' "$expect"
	printf 'output: %s\n' "$output"
	printf '\n'
done

if [ ! $ok ]; then
	exit 1;
fi
