name: build and test

on:
  push:
    branches: main
    paths:
      - include/*.h
      - src/*.c
      - Makefile
      - txt
      - .github/workflows/test.yml

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: install llvm
      run: sudo apt install llvm python3-dev

    - name: build aoc solutions
      run: make py_aoc

    - name: test aoc solutions
      run: ./test

    - name: dump stderr from log
      run: cat test.stderr
